# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line.

org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official

# BuildConfig
android.defaults.buildfeatures.buildconfig=true
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.renderscript=false
android.defaults.buildfeatures.resvalues=true
android.defaults.buildfeatures.shaders=false

# Compiler
android.useNewApkCreator=true

# Properties
APP_VERSION_CODE=1
APP_VERSION_NAME=1.0.0
APP_MIN_SDK=28
APP_TARGET_SDK=34
APP_COMPILE_SDK=34
